# Copyright 2024 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

set(CONFIG_ZB_USE_FREERTOS ON)
set(CONFIG_ZB_FREERTOS_CONFIG "${APPLICATION_SOURCE_DIR}/src/freertos/FreeRTOSConfig.h" CACHE STRING "")
set(CONFIG_ZB_TRACE_APP ON CACHE BOOL "Enable TRACE_APP logs")
set(CONFIG_ZB_TRACE_ZCL ON CACHE BOOL "Enable TRACE_ZCL logs")
set(CONFIG_ZB_USE_CLI ON CACHE BOOL "Enable CLI commands")