# Copyright 2024 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

set(CONFIG_ZB_USE_FREERTOS ON)
set(CONFIG_ZB_FREERTOS_CONFIG "${APPLICATION_SOURCE_DIR}/../../platform/${CONFIG_ZB_PLATFORM}/FreeRTOSConfig.h" CACHE STRING "")
set(CONFIG_ZB_TRACE_APP ON CACHE BOOL "Enable TRACE_APP logs")
set(CONFIG_ZB_TRACE_ZCL ON CACHE BOOL "Enable TRACE_ZCL logs")
set(CONFIG_ZB_USE_CLI ON CACHE BOOL "Enable CLI commands")
set(CONFIG_ZB_BOOTLOADER_MCUBOOT ON CACHE BOOL "This option signifies the target uses MCUBoot as a bootloader")
set(CONFIG_ZB_OTA_ENCRYPTION_KEY "1234567890ABCDEFA1B2C3D4E5F6F1B4" CACHE STRING "Key used to encrypt OTA image")
set(CONFIG_ZB_OTA_IMAGE_TYPE "0x0003" CACHE STRING "OTA image type")
string(TOUPPER "NXPZBROUTER-${CONFIG_ZB_BOARD}" CONFIG_ZB_OTA_VERSION_STR)
nxp_zb_pad_string(CONFIG_ZB_OTA_VERSION_STR ${CONFIG_ZB_OTA_VERSION_STR} "-" 32)
set(CONFIG_ZB_OTA_VERSION_STR ${CONFIG_ZB_OTA_VERSION_STR} CACHE STRING "OTA version string")